[package]
name = "rust-tutorial"
version = "0.1.0"
authors = ["loshy <loshy244110@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
